# Generated by Django 6.0.6 on 2026-08-11 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calendarevent_completed_calendarevent_event_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateWorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('local_evaluation', models.JSONField(blank=True, default=dict)),
                ('teacher_score', models.FloatField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('reviewed', 'Corrigé'), ('returned', 'À reprendre')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_work_submissions', to=settings.AUTH_USER_MODEL)),
                ('concourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_submissions', to='api.concours')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_submissions', to='api.resource')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_work_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
