# Generated by Django 6.0.6 on 2026-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Refusé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20),
        ),
    ]
